### ISSUE TITLE
(1) Remove `choly` 

### ISSUE THREAD

**Issue by FieryCod** [FieryCod/holy-lambda#20]
@ekoontz I will put the number on every task which will indicate the order in which they should be realized. Please let me know whether you are interested in doing it.

**Remove `choly` completely.**

The idea behind `choly` was to allow:
- automatic translation from template.yml (Java) -> native-template.yml (HCR)
  I think that this feature is buggy and over engineered. Most people will probably target HCR only and the translation is so simple that doing it by hand should not be problematic.

   Another thing is `choly template` supports only the AWS SAM which might suggest that HCR will work only with that tool **which is not true**.

- managing graalvm via the docker image
  This brings the new level of complexity which is not necessary for that small project.

- managing envs
  The core should not take care of managing the envs.

Let's keep `holy-lambda` as minimal runtime as it's only possible. 

**The core of the project should:**
- [X] allow execution in both runtimes (Java + HCR)
- [X] not include 3rd party libraries in it's core
- [X] support `reflect-config.json` generation via `native-agent` and `native-agent-payloads`
- [ ] support async mode (preferably via callback to not include 3rd party library like `core.async`)
- [ ] be as fast as possible (add benchmark)
- [ ] allow swap of default logger 
- [ ] not use any of dynamic bindings 
- [ ] provide tutorial how to develop and deploy simple lambda

**Comment by FieryCod** [comment]
@ekoontz any ideas?

**Comment by ekoontz** [comment]
Hi @FieryCod! I agree that it's a good start to remove choly and generally cleanup this repo to be as minimal as possible. I still have some basic questions:
- what does HCR mean? Is that a way to run lambdas locally (without AWS lambda)?
- how does `lein new holy-lambda <your-project-name>` work? I started with this, but there are some problems with projects generated this way - things don't work as expected. It seems like that deserves a new issue which I will be glad to open if you agree.

**Comment by ekoontz** [comment]
> automatic translation from template.yml (Java) -> native-template.yml (HCR)
I think that this feature is buggy and over engineered. Most people will probably target HCR only and the translation is so simple that doing it by hand should not be problematic.

PR for this here: https://github.com/FieryCod/holy-lambda/pull/22

**Comment by FieryCod** [comment]
1. Remove node.js completely. The dependency was to generate changelogs out of commits. We will generate changelogs by hand.
2. HCR is `Holy Custom Runtime`. Actually this project name is kind of a joke so probably we should either rename it or rename the runtime. HCR allows execution of lambdas on AWS via GraalVM without need of Java runtime. Actually the code allows run lambdas in two runtimes:
- Java 
- Native custom runtime (HCR)

**Comment by FieryCod** [comment]
@ekoontz Please notify me when you get rid of `choly` :)
