### ISSUE TITLE
(5) fix `lein new holy-lambda test-holy-lambda`

### ISSUE THREAD

**Issue by ekoontz** [FieryCod/holy-lambda#21]
This is an important entry point for beginners to understand how to use holy-lambda combine Clojure with AWS Lambda. It has some bugs that prevent new users from creating a basic beginning lambda. This issue will cover fixing this basic functionality.

**Comment by ekoontz** [comment]
Documentation for how to write leiningen templates: 

https://github.com/technomancy/leiningen/blob/master/doc/TEMPLATES.md

**Comment by FieryCod** [comment]
Regarding leiningen template here is the repo: https://github.com/FieryCod/holy-lambda-template.
Actually I'm thinking about replacing leiningen with tools.deps due to the simplicity of deps.edn.

**Comment by FieryCod** [comment]
@ekoontz We will stick with `leiningen` for some time. We should of course update the template but it's not a top priority. 

Async handlers, removal of default logger, benchmarks are top priorities for now :+1:

**Comment by FieryCod** [comment]
Done :) https://github.com/FieryCod/holy-lambda-template
