### ISSUE TITLE
tools.deps template

### ISSUE THREAD

**Issue by viesti** [FieryCod/holy-lambda#31]
This would allow using `deps.edn` as a Lambda project.

We'd probably need a Make target that does AOT compilation at least. Also, the JVM Runtime needs a way to generate a zip file.

To select between Leiningen and deps.edn, maybe provide an option to the lein new command than generates different scaffolding, e.g.:

```
lein new holy-lambda <my-lambda> :+tool.deps
```

A separate template project could be possible but would probably have a lot of duplication with the Leinigen template. Probably good to test that stuff works with [clj-new](https://github.com/seancorfield/clj-new).

**Comment by FieryCod** [comment]
Would you be interested in providing a PR? :)

**Comment by viesti** [comment]
Sure! Won't promise a schedule though :D

**Comment by FieryCod** [comment]
Yay. Great! Would love to get some help with relatively easy stuff. Thank you!

**Comment by FieryCod** [comment]
@viesti Starting from 0.1.45 template is fully deps.edn based.

**Comment by viesti** [comment]
Sweet! Thank you, I didn't even manage put my hands on the keyboard on this :D Will have to test this out :)
