### ISSUE TITLE
Add AWS lambda layer for babashka

### ISSUE THREAD

**Issue by FieryCod** [FieryCod/holy-lambda#32]
1. Publish layer on aws sam repo https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-publishing-applications.html

2. Get a verified author badge

3. Roll out a new release.

**Comment by viesti** [comment]
Apropos, I guess you are aware of this project? :) https://github.com/dainiusjocas/babashka-lambda-layer

Is the idea that this layer would only contain babashka itself and not the custom runtime event polling loop or other support code?

Another question also, which I noticed with babashka-lambda-layer is that how often would this layer be updated? It's neat that users could just acquire and use a babashka layer (and share it between Lambdas), but what if it doesn't get updated (as I guess happened with babashka-lambda-layer)? I guess it would be neat for users to have ways to themselves create and update a layer with babashka for their own AWS accounts, to allow updates own their own

Being part of babashka regular releases would probably be cool too, but might be good to talk to borkdude about this :)

**Comment by FieryCod** [comment]
I was not aware, but now I'm aware. 

The layer for babashka will include:
- babashka
- minimal holy-lambda jar without jsonista

Deploy scenario:
1. User marks holy-lambda as a provided dependency
2. User specifies ARN of holy-lambda-babashka-layer (holy-lambda minimal jar is already packed in it)
3. User runs make `USE_BB=true native-deploy`. Make automatically packs code into a .jar. Additional babashka dependencies should be added to native-deps/*.

Regarding releases of holy-lambda-babashka-layer for holy-lambda I will ensure that semanticVersioning will stay the same as holy-lambda version.

If somebody would like to add more dependencies then can do it via creating their own layer :)

**Comment by FieryCod** [comment]
@viesti Layer is available here: https://serverlessrepo.aws.amazon.com/applications/eu-central-1/443526418261/holy-lambda-babashka-runtime

Closing
