### ISSUE TITLE
Use babashka tasks instead of Makefile

### ISSUE THREAD

**Issue by FieryCod** [FieryCod/holy-lambda#36]

**Comment by ekoontz** [comment]
Found some documentation for babashka tasks here: https://github.com/babashka/babashka/issues/778

**Comment by FieryCod** [comment]
@ekoontz I'm experimenting with bb tasks in this module: https://github.com/FieryCod/holy-lambda/tree/master/modules/holy-lambda-babashka-tasks

You can run `bb tasks` there and check it out. Some tasks are in-progress, but some works.
![image](https://user-images.githubusercontent.com/14275210/116004583-afd4be80-a603-11eb-86b6-b0d571b2323b.png)


Example: bb doctor
![image](https://user-images.githubusercontent.com/14275210/116004597-c7ac4280-a603-11eb-9588-a0c554d1b200.png)

**Comment by FieryCod** [comment]
@ekoontz Done :) You can check new version of holy-lambda ;)
