### ISSUE TITLE
template is missing Makefile

### ISSUE THREAD

**Issue by lowecg** [FieryCod/holy-lambda#42]
I may be using this feature prematurely, but the lein template does not appear to include a `Makefile`:

```
lein new holy-lambda getting_started
cd getting_started/
make dry-api
make: *** No rule to make target `dry-api'.  Stop.

$ ls
README.md	bb.edn		deps.edn	envs.json	resources	src		template.yml
```

PS This looks like being a really useful project, thank you for making it available.
PPS Any chance of publishing the work so far for the "getting started" guide?

**Comment by FieryCod** [comment]
Makefile is no longer used. 

There are two reasons for that:
1. It was hard for me to manage multiple versions of makefile and support all 3 runtimes.
2. Users were not interested in using makefile. It was very complex.

Makefile has been replaced via `bb tasks` for which you need `babashka` to be installed. 
On new project just run first:
`bb stack:sync` and if any steps are failing then `bb stack:doctor` becomes handy. 

Full list of tasks with documentation is available when running `bb tasks`. 

I am aware that documentation is rather bad and I'm working to improve it.

**Comment by lowecg** [comment]
Thank you, that makes sense.

I've installed babashka and I've joined the Clojurian channel. It would be good to contribute if I can.
