### ISSUE TITLE
Check if docker is running before stack:sync

### ISSUE THREAD

**Issue by FieryCod** [FieryCod/holy-lambda#45]
For MacOS:
```
pgrep -f Docker.app > /dev/null || echo "Docker is not running!"
```

For Linux:
```
pgrep -f docker > /dev/null || echo "Docker is not running!"
```

**Comment by galderz** [comment]
You should not assume macos users have `Docker.app` installed. This is a premium app now and a lot of users have switched to free alternatives, e.g. [Colima](https://github.com/abiosoft/colima).

**Comment by FieryCod** [comment]
@galderz Thx. Most of the `tasks` code will be deprecated soon and replaced with Clojure `tools.build` programmatic API. I took note of your comment. All the best!

**Comment by ccfontes** [comment]
I'm using Podman and obviously won't work using the Docker.app check.
