### ISSUE TITLE
Tutorial expects creation of a REST API, but template.yml creates an HTTP API

### ISSUE THREAD

**Issue by JonathanHarford** [FieryCod/holy-lambda#67]
It looks as though the tutorial (specifically [End to End: Calling the Lambda from API Gateway](https://cljdoc.org/d/io.github.FieryCod/holy-lambda/0.2.1/doc/tutorial/getting-started#end-to-end-calling-the-lambda-from-api-gateway)) was never updated to match [this](https://github.com/FieryCod/holy-lambda/commit/3dd66eebbd6f6bd184ee7c6c12e3e629d95169cb) commit.

**Comment by FieryCod** [comment]
Feel free to propose the PR ;)

**Comment by FieryCod** [comment]
@JonathanHarford Thanks for letting me know. I'm working on the new version of the documentation. I will close the issue when it's ready!

**Comment by FieryCod** [comment]
@JonathanHarford Thank you so much. I have just fixed it. You can check the new version of documentation here: https://fierycod.github.io/holy-lambda/#/babashka-backend-tutorial
