### ISSUE TITLE
Linked documentation is not available.

### ISSUE THREAD

**Issue by sbenhaim** [FieryCod/holy-lambda#71]
**Describe the bug**
The documentation linked from the README is unavailable. 

Page reports "API & Git import failed in build #47800" and error is reported as "java.lang.OutOfMemoryError: Java heap space"

**To Reproduce**
Click on doc link in README or navigate to https://cljdoc.org/d/io.github.FieryCod/holy-lambda/0.3.0/doc/tutorial.

**Expected behavior**
Docs.

**Screenshots**
![holy-lambda](https://user-images.githubusercontent.com/6322/132137196-1c92fff1-e9e1-4596-a211-d21848f3df19.png)

**Extra information:**
Works if I navigate to version 0.2.1.

**Comment by FieryCod** [comment]
@sbenhaim Thank you very much for raising this issue. I have updated the documentation. 

https://fierycod.github.io/holy-lambda
