### ISSUE TITLE
[FEATURE] higher version for babashka runtime

### ISSUE THREAD

**Issue by benjamin-asdf** [FieryCod/holy-lambda#85]
I crave 0.7.8 for specter support. My use case is to put an existing cli tool as a lambda.

**Comment by FieryCod** [comment]
Hi, 

I have updated the layer to 0.9.162. Cheers!
https://serverlessrepo.aws.amazon.com/applications/eu-central-1/443526418261/holy-lambda-babashka-runtime-amd64
